# -*- coding: utf-8 -*-
"""GPT-4 API 실습 (wikidocs).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zab0ghQ5Y-1RONpwQvEbg7kiLOvLf9s-
"""

pip install openai

import openai
client = openai.OpenAI(api_key="여러분의 키 값")

response = client.chat.completions.create(
    model="gpt-4o",
    messages=[
        {"role": "user", "content": "2020년 월드시리즈에서는 누가 우승했어?"}
    ]
)

# 답변을 받는 방법
print(response.choices[0].message.content)

response = client.chat.completions.create(
    model="gpt-4o",
    messages=[
        {"role": "system", "content": "너는 친절하게 답변해주는 비서야. 답변은 반말로 해줘"},
        {"role": "user", "content": "2020년 월드시리즈에서는 누가 우승했어?"}
    ]
)

# 답변을 받는 방법
print(response.choices[0].message.content)

response = client.chat.completions.create(
    model="gpt-4o",
    messages=[
        {"role": "user", "content": "2002년 월드컵에서 가장 화제가 되었던 나라는 어디야?"},
        {"role": "assistant", "content": "바로 예상을 뚫고 4강 진출 신화를 일으킨 한국입니다."},
        {"role": "user", "content": "그 나라가 화제가 되었던 이유를 자세하게 설명해줘"}
    ]
)

print(response.choices[0].message.content)