# -*- coding: utf-8 -*-
"""한국은행 금융 챗봇 wikidocs - 25-06-26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ep5RR1L-VOCAR0rC4j9uLduaHzr73mvN
"""

!pip install langchain_openai langchain_community pypdf chromadb

import os
from langchain_openai import ChatOpenAI
from langchain.prompts import PromptTemplate
from langchain.vectorstores import Chroma
from langchain.embeddings import OpenAIEmbeddings
from langchain.chains import RetrievalQA
from langchain.document_loaders import PyPDFLoader
import urllib.request
import gradio as gr

os.environ['OPENAI_API_KEY'] = "여러분이 발급받은 오픈AI API 키 값"

urllib.request.urlretrieve("https://github.com/chatgpt-kr/openai-api-tutorial/raw/main/ch07/2020_%EA%B2%BD%EC%A0%9C%EA%B8%88%EC%9C%B5%EC%9A%A9%EC%96%B4%20700%EC%84%A0_%EA%B2%8C%EC%8B%9C.pdf", filename="2020_경제금융용어 700선_게시.pdf")

loader = PyPDFLoader("2020_경제금융용어 700선_게시.pdf")
texts = loader.load_and_split()
print('문서의 수 :', len(texts))

texts[15]

print(texts[15].page_content)

print(texts[0].page_content)

print(texts[5].page_content)

print(texts[12].page_content)

print(texts[13].page_content)

texts = texts[13:]
print('줄어든 청크의 개수:', len(texts))

print('첫번째 청크 출력 :', texts[0])

print('마지막 청크 출력 :', texts[-1])

print('마지막에서 두번째 청크 출력 :', texts[-2])

texts = texts[:-1]
print('마지막 데이터 제거 후 청크의 개수:', len(texts))

embedding = OpenAIEmbeddings(chunk_size=100)

vectordb = Chroma.from_documents(
    documents=texts,
    embedding=embedding)

print(vectordb._collection.count())

for key in vectordb._collection.get():
  print(key)

documents = vectordb._collection.get()['documents']
print('청크의 개수 :', len(documents))
print('-' * 50)
print('0번 청크 출력 :', documents[0])

embeddings = vectordb._collection.get(include=['embeddings'])['embeddings']
print('임베딩 벡터의 개수 :', len(embeddings))

print('0번 청크의 임베딩 값 출력 :', embeddings[0])
print('0번 청크의 임베딩 값의 길이 :', len(embeddings[0]))

metadatas = vectordb._collection.get()['metadatas']
print('metadatas의 개수 :', len(metadatas))
print('0번 청크의 출처 :', metadatas[0])

retriever = vectordb.as_retriever(search_kwargs={"k": 2})

docs = retriever.get_relevant_documents("비트코인이 궁금해")
print('유사 문서 개수 :', len(docs))
print('--' * 20)
print('첫번째 유사 문서 :', docs[0])
print('두번째 유사 문서 :', docs[1])

template = """당신은 한국은행에서 만든 금융 용어를 설명해주는 금융쟁이입니다.
안상준 개발자가 만들었습니다. 주어진 검색 결과를 바탕으로 답변하세요.
검색 결과에 없는 내용이라면 답변할 수 없다고 하세요. 반말로 친근하게 답변하세요.
{context}

Question: {question}
Answer:
"""

prompt = PromptTemplate.from_template(template)

llm = ChatOpenAI(model_name="gpt-4o", temperature=0)

qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type_kwargs={"prompt": prompt},
    retriever=retriever,
    return_source_documents=True)

input_text = "디커플링이란 무엇인가?"
chatbot_response = qa_chain(input_text)
print(chatbot_response)

def get_chatbot_response(input_text):
    chatbot_response = qa_chain(input_text)
    return chatbot_response['result'].strip()

input_text = "너는 뭘하는 챗봇이니?"
result = get_chatbot_response(input_text)
print(result)

input_text = "비트코인에 대해서 궁금하당~"
result = get_chatbot_response(input_text)
print(result)

# 인터페이스 생성
with gr.Blocks() as demo:
    chatbot = gr.Chatbot(label="경제금융용어 챗봇") # 챗봇 레이블을 좌측 상단에 구성
    msg = gr.Textbox(label="질문해주세요!")  # 하단의 채팅창 레이블
    clear = gr.Button("대화 초기화")  # 대화 초기화 버튼

    # 챗봇의 답변을 처리하는 함수
    def respond(message, chat_history):
      result = qa_chain(message)
      bot_message = result['result']

      # 채팅 기록에 사용자의 메시지와 봇의 응답을 추가
      chat_history.append((message, bot_message))
      return "", chat_history

    # 사용자의 입력을 제출(submit)하면 respond 함수가 호출
    msg.submit(respond, [msg, chatbot], [msg, chatbot])

    # '초기화' 버튼을 클릭하면 채팅 기록을 초기화
    clear.click(lambda: None, None, chatbot, queue=False)

# 인터페이스 실행
demo.launch(debug=True)